### ISSUE TITLE
Migrate the site from Mobirise

### ISSUE THREAD

**Issue by avive** [spacemeshos/spacemesh.io#1]
We'd like to migrate [our website](https://spacemesh.io) from Mobirise to React.js / Bootstrap so we can internationalize it by localizing it to multiple languages. 

# requirements
- Fully responsive design - must look great on mobile and on desktop
- Copy existing site functionality - 1 landing page + additional static secondary pages.
- Use node.js / express as the backend
- Integrate mailchimp registration for Spacemesh updates.

**Comment by ImmanuelSegol** [comment]
Hi,
I'm new here, my name is Immanuel I'm a fullstack developer golang/nodejs/express/react.

I would be love to help :)
